image: ruby:2.5.7

services:
  - postgres:13-alpine

variables:
  POSTGRES_DB: ./docker/db_config.env
  CONTAINER_IMAGE: docker-compose.yml

stages:
  - build
  - test-front

cache:
  paths:
    - .bundle
    - vendor/ruby

build:
  stage: build

  services:
    - docker:dind
  image:
    name: docker/compose:latest
  script:
    - docker-compose up --build -d
  before_script:
    - docker version
    - docker-compose --version

test-front:
  stage: test-front
  script:
    - docker-compose run --rm frontend && yarn run test:unit