image: docker/compose:latest

services:
  - docker:stable-dind
before_script:
  - apk update
  - apk add ruby-dev

stages:
  - staging
  - build
  - test-front
  - test-back

staging:
  type: deploy
  stage: staging
  image: ruby:2.5.7
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - test_deploy

build:
  stage: build
  script:
    - docker-compose up --build -d

test-front:
  stage: test-front
  script:
    - docker-compose run frontend sh -c "yarn install && yarn run test:unit"


test-back:
  stage: test-back
  script:
    - docker-compose run api sh -c "gem install bundler && bundle install && rake db:create && rails db:migrate && bundle exec rails test"
