image: docker/compose:latest

services:
  - docker:stable-dind
before_script:
  - docker version
  - docker-compose --version

stages:
  - build
  - test-front
  - test-back

build:
  stage: build
  script:
    - docker-compose up --build -d

test-front:
  stage: test-front
  script:
    - docker-compose run frontend sh -c "yarn install && yarn run test:unit"

test-back:
  stage: test-back
  script:
    - docker-compose run api sh -c "gem install bundler && bundle install && rake db:create && rails db:migrate && bundle exec rails test"
