image: docker/compose:latest

services:
  - docker:stable-dind
before_script:
  - docker version
  - docker-compose --version
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - staging
  - build
  - test-front
  - test-back

build:
  stage: build
  script:
    - docker-compose up --build -d

test-front:
  stage: test-front
  script:
    - docker-compose run frontend sh -c "yarn install && yarn run test:unit"

test-back:
  stage: test-back
  script:
    - docker-compose run api sh -c "gem install bundler && bundle install && rake db:create && rails db:migrate && bundle exec rails test"

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - test_deploy