image: docker/compose:latest

services:
  - postgres:13-alpine
  - docker:dind
before_script:
  - docker version
  - docker-compose --version

variables:
  POSTGRES_DB: ./docker/db_config.env
  CONTAINER_IMAGE: docker-compose.yml

stages:
  - build-front
  - test-front

cache:
  paths:
    - .bundle
    - vendor/ruby

build-front:
  stage: build-front

  script:
    - docker-compose up --build -d

test-front:
  stage: test-front
  script:
    - docker-compose run frontend ./scripts/front_tests.sh