version: "3.7"

services:
  frontend:
    image: node:12-alpine
    command: sh -c "yarn install && yarn dev"
    ports:
      - 8080:8080
    working_dir: /frontend/client/
    volumes:
      - ./:/frontend
